### PR TITLE
Set up package and development tooling

### PR DESCRIPTION
**Pull request by tomalrussell**
- adds nird package
- adds tests
- configures formatting, linting, type-checking
- runs tests and checks in GitHub Actions

### CODE REVIEW

**Comment by itrcrisks** [comment]
git clone did not work. probably do url should not have : instead /

**Comment by YueeeeeLi** [comment]
micromamba failed to install everything on Windows!

```
Installing pip packages: ruff, mypy
The system cannot find the path specified.
critical libmamba pip failed to install packages
```

**Comment by tomalrussell** [comment]
> git clone did not work. probably do url should not have : instead /

Thanks! I added a note with the HTTPS option.

**Comment by tomalrussell** [comment]
> micromamba failed to install everything on Windows!

Can you pull the latest and try again? I think we need `pip` explicitly as a dependency in the `environment.yaml` before specifying pip packages to install.

**Comment by YueeeeeLi** [comment]
still get an error:

```
Installing pip packages: ruff, mypy
info     libmamba Calling: C:\Users\...\micromamba\envs\nird\python.exe -m pip install -r C:\Oxford\Research\DAFNI\DAFNI-NIRD\mambaf5NgzkSsTLx --no-input
The system cannot find the path specified.
critical libmamba pip failed to install packages
```

workaround is to run pip directly

```
micromamba activate nerd
pip install ruff mypy --editable .
```

**Pull request merged**
